version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: youngbindb
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data