version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data